#pragma once

#include <map>
#include <string>

namespace minecraft
{
    enum class EntityMetadataType
    {
        AREA_EFFECT_CLOUD = 0,
        ARMOR_STAND = 1,
        ARROW = 2,
        AXOLOTL = 3,
        BAT = 4,
        BEE = 5,
        BLAZE = 6,
        BOAT = 7,
        CAT = 8,
        CAVE_SPIDER = 9,
        CHICKEN = 10,
        COD = 11,
        COW = 12,
        CREEPER = 13,
        DOLPHIN = 14,
        DONKEY = 15,
        DRAGON_FIREBALL = 16,
        DROWNED = 17,
        ELDER_GUARDIAN = 18,
        END_CRYSTAL = 19,
        ENDER_DRAGON = 20,
        ENDERMAN = 21,
        ENDERMITE = 22,
        EVOKER = 23,
        EVOKER_FANGS = 24,
        EXPERIENCE_ORB = 25,
        EYE_OF_ENDER = 26,
        FALLING_BLOCK = 27,
        FIREWORK_ROCKET_ENTITY = 28,
        FOX = 29,
        GHAST = 30,
        GIANT = 31,
        GLOW_ITEM_FRAME = 32,
        GLOW_SQUID = 33,
        GOAT = 34,
        GUARDIAN = 35,
        HOGLIN = 36,
        HORSE = 37,
        HUSK = 38,
        ILLUSIONER = 39,
        IRON_GOLEM = 40,
        ITEM = 41,
        ITEM_FRAME = 42,
        FIREBALL = 43,
        LEASH_KNOT = 44,
        LIGHTNING_BOLT = 45,
        LLAMA = 46,
        LLAMA_SPIT = 47,
        MAGMA_CUBE = 48,
        MARKER = 49,
        MINECART = 50,
        MINECART_CHEST = 51,
        MINECART_COMMAND_BLOCK = 52,
        MINECART_FURNACE = 53,
        MINECART_HOPPER = 54,
        MINECART_SPAWNER = 55,
        MINECART_TNT = 56,
        MULE = 57,
        MOOSHROOM = 58,
        OCELOT = 59,
        PAINTING = 60,
        PANDA = 61,
        PARROT = 62,
        PHANTOM = 63,
        PIG = 64,
        PIGLIN = 65,
        PIGLIN_BRUTE = 66,
        PILLAGER = 67,
        POLAR_BEAR = 68,
        PRIMED_TNT = 69,
        PUFFERFISH = 70,
        RABBIT = 71,
        RAVAGER = 72,
        SALMON = 73,
        SHEEP = 74,
        SHULKER = 75,
        SHULKER_BULLET = 76,
        SILVERFISH = 77,
        SKELETON = 78,
        SKELETON_HORSE = 79,
        SLIME = 80,
        SMALL_FIREBALL = 81,
        SNOW_GOLEM = 82,
        SNOWBALL = 83,
        SPECTRAL_ARROW = 84,
        SPIDER = 85,
        SQUID = 86,
        STRAY = 87,
        STRIDER = 88,
        THROWN_EGG = 89,
        THROWN_ENDER_PEARL = 90,
        THROWN_EXPIERIENCE_BOTTLE = 91,
        THROWN_POTION = 92,
        THROWN_TRIDENT = 93,
        TRADER_LLAMA = 94,
        TROPICAL_FISH = 95,
        TURTLE = 96,
        VEX = 97,
        VILLAGER = 98,
        VINDICATOR = 99,
        WANDERING_TRADER = 100,
        WITCH = 101,
        WITHER = 102,
        WITHER_SKELETON = 103,
        WITHER_SKULL = 104,
        WOLF = 105,
        ZOGLIN = 106,
        ZOMBIE = 107,
        ZOMBIE_HORSE = 108,
        ZOMBIE_VILLAGER = 109,
        ZOMBIFIED_PIGLIN = 110,
        PLAYER = 111,
        FISHING_HOOK = 112,
    };

    extern std::map<EntityMetadataType, std::string> ENTITY_TYPE_TO_STRING;
    extern std::map<std::string, EntityMetadataType> STRING_TO_ENTITY_TYPE;
}